name: Alfred Kam
markdown: redcarpet
highlighter: pygments
baseurl:
permalink: /:title
paginate: 5
paginate_path: /page:num
description: Ups and Downs of Entrepreneurship
url: http://www.alfredkam.com