baseurl = "http://alfredkam.com"
languageCode = "en-us"
title = "Alfred kam"
description = "Entrepreneurship, Engineering and Coffee"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

[indexes]
  tag = "tags"
